Alunos: Anderson Silva, Mariana Rodrigues

R.A: 2150875, 2151014

## Exercício 1

Estude os detalhes de Pytorch. Garanta que você entendeu os conceitos básicos exemplificados.

## Exercício 2

Considere esses valores abaixo para os tensores x e y:

In [1]:
import torch
torch.manual_seed(0)

#Shape (10, 3)
x = torch.randn(10, 3)
print(x)

#Shape(10, 2)
y = torch.randn(10, 2)
print(y)


tensor([[-1.1258, -1.1524, -0.2506],
        [-0.4339,  0.8487,  0.6920],
        [-0.3160, -2.1152,  0.3223],
        [-1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377, -0.1435],
        [-0.1116, -0.6136,  0.0316],
        [-0.4927,  0.2484,  0.4397],
        [ 0.1124, -0.8411, -2.3160],
        [-0.1023,  0.7924, -0.2897],
        [ 0.0525,  0.5229,  2.3022]])
tensor([[ 0.9383,  0.4889],
        [-0.6731,  0.8728],
        [ 1.1108,  1.2899],
        [-1.4782,  2.5672],
        [-0.4731,  0.3356],
        [ 1.5091,  2.0820],
        [-0.4798, -0.4997],
        [-1.0670,  1.1149],
        [-0.1407,  0.8058],
        [ 0.3276, -0.7607]])


Modifique o "Primeiro modelo" exemplificado no notebook criando um loop para repetir 1000 vezes os passos chave que foram repetidos duas vezes no exemplo com duas repetições. Como ficou o resultado?

In [5]:
import torch
import torch.nn as nn

torch.manual_seed(0)

x = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2)

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Usando {}".format(device))

linear = linear.to(device)
x = x.to(device)
y = y.to(device)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(linear.parameters(), lr=0.001)

for epoch in range(1000):
    pred = linear(x)

    loss = criterion(pred, y)

    optimizer.zero_grad()  # Zerar gradientes
    loss.backward()  # Retropropagação
    optimizer.step()  # Atualizar parâmetros

    if (epoch + 1) % 100 == 0:
        print(f'Época [{epoch + 1}/1000], Perda: {loss.item():.4f}')

# Resultado final
print('Parâmetros finais do modelo:')
print('Pesos (w):', linear.weight)
print('Viés (b):', linear.bias)


Usando cpu
Época [100/1000], Perda: 1.1035
Época [200/1000], Perda: 0.9581
Época [300/1000], Perda: 0.8488
Época [400/1000], Perda: 0.7642
Época [500/1000], Perda: 0.6987
Época [600/1000], Perda: 0.6485
Época [700/1000], Perda: 0.6107
Época [800/1000], Perda: 0.5828
Época [900/1000], Perda: 0.5628
Época [1000/1000], Perda: 0.5488
Parâmetros finais do modelo:
Pesos (w): Parameter containing:
tensor([[ 0.6020, -0.6985,  0.4268],
        [-0.7545, -0.1253, -0.3178]], requires_grad=True)
Viés (b): Parameter containing:
tensor([0.0745, 0.3573], requires_grad=True)
